// Generated by Website Factory (GaLaBau vertical). Update via the factory pipeline, not by hand.

export type GalabauUnit = "qm" | "lfm" | "stk" | "pauschal";

export type GalabauServiceKey =
  | "gartenneugestaltung"
  | "pflasterarbeiten"
  | "terrassenbau"
  | "gartenpflege"
  | "zaun-sichtschutz"
  | "bewaesserung"
  | "baumpflege"
  | "gewerbeflaechen";

export type GalabauService = {
  key: GalabauServiceKey;
  slug: string;
  label: string;
  navLabel: string;
  cta: string;
  unit: GalabauUnit;
  teaser: string;
  intro: string;
  bullets: string[];
  ablauf: { title: string; text: string }[];
  faq: { q: string; a: string }[];
  image: string;
  estimate: { minPerUnit: number; maxPerUnit: number; baseMin: number };
  seo: { title: string; description: string };
};

export type GalabauBudgetBand = {
  id: string;
  label: string;
  min: number;
  max: number | null;
};

export type GalabauConfig = {
  company: {
    name: string;
    city: string;
    foundedYear: string;
    teamSize: string;
    machines: string;
  };
  claim: string;
  heroSubline: string;
  services: GalabauService[];
  serviceArea: {
    centerCity: string;
    radiusKm: number;
    note: string;
    plzPrefixes: string[];
    borderPlzPrefixes: string[];
    places: string[];
    /** Map centre from the Google profile. Without it the map is skipped. */
    center?: { lat: number; lng: number };
  };
  contact: {
    phone: string;
    phoneLink: string;
    whatsapp: string;
    whatsappLink: string;
    whatsappPrefill: string;
    email: string;
    leadEmail: string;
  };
  estimator: {
    enabled: boolean;
    minProjectEur: number;
    currency: string;
    roundingStep: number;
    disclaimer: string;
    sizeThresholds: { klein: number; mittel: number };
    surcharges: { hanglage: number; schwererZugang: number; rueckbauBestand: number };
    budgetBands: GalabauBudgetBand[];
    realismQuestion: string;
    realismOptions: { id: string; label: string }[];
  };
  recruiting: {
    enabled: boolean;
    headline: string;
    teaser: string;
    intro: string;
    roles: string[];
    benefits: string[];
  };
  trust: {
    seals: { label: string; note: string }[];
    usps: { label: string; text: string }[];
  };
  assistant: {
    enabled: boolean;
    photoUploadMaxFiles: number;
    photoUploadMaxMb: number;
    consentText: string;
    responsePromise: string;
  };
};

export const galabau: GalabauConfig = {
  "company": {
    "name": "Zogaj Garten & Landschaftsbau",
    "city": "Sinsheim",
    "foundedYear": "",
    "teamSize": "",
    "machines": ""
  },
  "claim": "Zogaj Garten & Landschaftsbau in Sinsheim",
  "heroSubline": "Hofeinfahrten, Wege, Terrassen und komplette Gartenanlagen. Vom Aushub bis zur letzten Fuge, im Umkreis von rund 40 km um Sinsheim.",
  "services": [
    {
      "key": "pflasterarbeiten",
      "slug": "pflasterarbeiten",
      "label": "Pflasterarbeiten",
      "navLabel": "Pflaster",
      "cta": "Fläche einschätzen lassen",
      "unit": "qm",
      "teaser": "Hofeinfahrt, Wege und Hofflächen: alte Fläche raus, tragfähiger Unterbau rein, Gefälle und Entwässerung geplant.",
      "intro": "Pflaster ist die Arbeit, nach der man uns am häufigsten fragt. Wie lange eine Fläche hält, entscheidet sich unter dem Stein: Tragschicht, Verdichtung, Gefälle. Deshalb tragen wir den alten Aufbau in der Regel ab, statt neue Steine auf gesetzten Untergrund zu legen. Eine Hofeinfahrt von rund 160 qm haben wir so in zwei Wochen abgetragen und neu gepflastert. Den Zeitrahmen für Ihre Fläche legen wir vor Baubeginn fest.",
      "bullets": [
        "Hofeinfahrt, Zufahrt, Wege, Hof- und Stellflächen",
        "Rückbau der alten Fläche, Aushub und Entsorgung inklusive",
        "Unterbau nach Belastung: PKW, Wohnmobil oder Lieferverkehr",
        "Gefälle, Rinnen und sauberer Anschluss an Bestandsflächen",
        "Randeinfassungen, Muster, Betonstein und Naturstein"
      ],
      "ablauf": [
        {
          "title": "Fläche melden",
          "text": "Quadratmeter grob schätzen oder Fotos schicken, wir rechnen die Fläche nach."
        },
        {
          "title": "Besichtigung vor Ort",
          "text": "Wir klären Belastung, Untergrund, Zufahrt und Entwässerung und wählen den passenden Aufbau."
        },
        {
          "title": "Angebot",
          "text": "Positionen für Aushub, Entsorgung, Tragschicht, Material und Einbau, getrennt ausgewiesen."
        },
        {
          "title": "Einbau",
          "text": "Aushub, Verdichtung, Verlegung, Abrütteln und Verfugen mit sauberer Baustellenübergabe."
        }
      ],
      "faq": [
        {
          "q": "Muss die alte Fläche raus?",
          "a": "Meist ja. Ein neues Pflaster auf altem, gesetztem Unterbau bekommt früher oder später Spurrillen. Wir prüfen den Bestand und sagen offen, ob ein Rückbau nötig ist."
        },
        {
          "q": "Wie viel Gefälle braucht die Fläche?",
          "a": "Als Faustwert rund zwei Prozent, weg vom Gebäude. Wo das nicht geht, planen wir Rinnen oder Versickerung ein."
        }
      ],
      "image": "/assets/acquisition/baustellen/baustelle-mit-haus-und-pflasterung-01.jpg",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 210,
        "baseMin": 3000
      },
      "seo": {
        "title": "Pflasterarbeiten in Sinsheim | Zogaj Garten & Landschaftsbau",
        "description": "Pflasterarbeiten für Hofeinfahrt, Wege und Hofflächen in Sinsheim: Rückbau, tragfähiger Unterbau, geplante Entwässerung."
      }
    },
    {
      "key": "gartenneugestaltung",
      "slug": "gartenneugestaltung",
      "label": "Gartenneugestaltung",
      "navLabel": "Gartengestaltung",
      "cta": "Projekt planen lassen",
      "unit": "qm",
      "teaser": "Vom alten Garten oder leeren Grundstück zur fertigen Anlage: Erdarbeiten, Wege, Mauern, Beete und Rasen.",
      "intro": "Eine Neugestaltung ist selten nur Bepflanzung. Meist gehören Rückbau, Erdarbeiten, Entwässerung, Wege und eine Terrasse dazu. Wir machen das in einem Zug, damit die Gewerke aufeinander passen. Wenn sich während der Bauzeit etwas ändert, halten wir es schriftlich fest und rechnen es offen ab.",
      "bullets": [
        "Aufmaß vor Ort: Boden, Gefälle, Zufahrt und Bestand",
        "Rückbau, Erdarbeiten und Entsorgung des Aushubs",
        "Wege, Terrasse, Mauern, Pflanzflächen und Rollrasen aus einer Hand",
        "Änderungswünsche während der Bauzeit halten wir schriftlich fest",
        "Budgetspannen dienen ausschließlich der ersten Orientierung"
      ],
      "ablauf": [
        {
          "title": "Anfrage",
          "text": "Sie schildern Fläche, Zustand und Wunsch über den Projekt-Assistenten, idealerweise mit Fotos."
        },
        {
          "title": "Termin vor Ort",
          "text": "Wir messen auf, prüfen Zugang, Boden und Gefälle und klären, was baulich sinnvoll ist."
        },
        {
          "title": "Planung & Angebot",
          "text": "Sie bekommen eine nachvollziehbare Planung mit Positionen, nicht nur eine Endsumme."
        },
        {
          "title": "Ausführung",
          "text": "Feste Bauzeit, ein Ansprechpartner, saubere Übergabe inklusive Pflegehinweisen."
        }
      ],
      "faq": [
        {
          "q": "Was kostet eine Gartenneugestaltung?",
          "a": "Das hängt stark von Fläche, Untergrund, Zugang und Material ab. Deshalb nennen wir online nur grobe Orientierungsrahmen und den verbindlichen Preis erst nach dem Aufmaß vor Ort."
        },
        {
          "q": "Wie lange dauert so ein Projekt?",
          "a": "Kleinere Umgestaltungen dauern wenige Tage, komplette Neuanlagen mit Erdarbeiten und Terrasse meist mehrere Wochen. Den Zeitrahmen legen wir vor Baubeginn fest."
        }
      ],
      "image": "/assets/acquisition/projekte/vorgarten-mit-bepflanzung-und-pflaster-01.jpg",
      "estimate": {
        "minPerUnit": 120,
        "maxPerUnit": 320,
        "baseMin": 4000
      },
      "seo": {
        "title": "Gartenneugestaltung in Sinsheim | Zogaj Garten & Landschaftsbau",
        "description": "Gartenneugestaltung mit Erdarbeiten, Wegen, Mauern und Bepflanzung. Aufmaß vor Ort, klare Positionen, feste Bauzeit."
      }
    },
    {
      "key": "terrassenbau",
      "slug": "terrassenbau",
      "label": "Terrassenbau",
      "navLabel": "Terrasse",
      "cta": "Terrasse anfragen",
      "unit": "qm",
      "teaser": "Terrassen aus Großformatplatten, Naturstein oder Keramik, mit passendem Unterbau und sauberem Randabschluss.",
      "intro": "Die Terrasse ist die Fläche, die täglich benutzt wird. Ob sie nach fünf Jahren noch eben liegt, entscheiden Unterbau, Gefälle und Randabschluss, nicht das Muster im Prospekt. Wir bauen im Splittbett oder auf Stelzlagern und ziehen den Übergang zu Weg, Pflaster und Rasen gleich mit.",
      "bullets": [
        "Großformatplatten, Naturstein, Keramik und Betonplatten",
        "Unterbau im Splittbett, auf Stelzlagern oder Punktfundamenten",
        "Anschlusshöhen an Türschwelle und Hauswand vorab geprüft",
        "Übergang zu Pflasterweg, Kiesfläche und Rasen mitgeplant",
        "Sichtschutz und Randeinfassung auf Wunsch im selben Zug"
      ],
      "ablauf": [
        {
          "title": "Wunsch klären",
          "text": "Größe, Nutzung, Sonne und gewünschtes Material, gern mit Fotos der jetzigen Fläche."
        },
        {
          "title": "Untergrund prüfen",
          "text": "Wir schauen uns Anschlusshöhen, Türschwellen und Entwässerung vor Ort an."
        },
        {
          "title": "Angebot",
          "text": "Unterbau, Belag und Zusatzarbeiten wie Randeinfassung getrennt kalkuliert."
        },
        {
          "title": "Bau",
          "text": "Unterbau, Belag, Randabschluss, Reinigung und Übergabe."
        }
      ],
      "faq": [
        {
          "q": "Welches Material passt zu meiner Terrasse?",
          "a": "Großformatplatten wirken ruhig und sind pflegeleicht, Naturstein ist lebendiger und verzeiht Kanten eher. Beim Ortstermin sehen wir uns Haus, Fläche und Nutzung an und sagen, was dazu passt."
        },
        {
          "q": "Geht das auch auf einer bestehenden Platte?",
          "a": "Oft ja, mit Stelzlagern. Voraussetzung ist eine ausreichende Aufbauhöhe an der Tür und ein funktionierendes Gefälle."
        }
      ],
      "image": "/assets/acquisition/baustellen/gartenweg-mit-geometrischem-pflaster-01.jpg",
      "estimate": {
        "minPerUnit": 140,
        "maxPerUnit": 380,
        "baseMin": 3500
      },
      "seo": {
        "title": "Terrassenbau in Sinsheim | Zogaj Garten & Landschaftsbau",
        "description": "Terrassenbau in Sinsheim mit Großformatplatten, Naturstein oder Keramik: geplanter Unterbau, Gefälle und sauberer Randabschluss."
      }
    },
    {
      "key": "gartenpflege",
      "slug": "gartenpflege",
      "label": "Gartenpflege",
      "navLabel": "Pflege",
      "cta": "Pflege anfragen",
      "unit": "qm",
      "teaser": "Einmaliger Einsatz oder feste Termine über die Saison: Rasen, Rollrasen, Hecken, Sträucher und Entsorgung.",
      "intro": "Pflege ist planbar. Wer feste Termine hat, spart sich den Rückschnitt-Notfall im Sommer. Wir übernehmen beides: den einmaligen Einsatz, wenn der Garten aus dem Ruder gelaufen ist, und die laufende Pflege über die Saison. Schnittgut und Grünabfall nehmen wir mit.",
      "bullets": [
        "Einmalpflege für verwilderte Gärten inklusive Entsorgung",
        "Pflegevertrag mit festen Terminen über die Saison",
        "Rasen mähen, vertikutieren, nachsäen und düngen",
        "Rollrasen verlegen, alten Rasen abtragen und entsorgen",
        "Hecken, Sträucher und Bodendecker schneiden, Schnittgut kommt mit"
      ],
      "ablauf": [
        {
          "title": "Bestand ansehen",
          "text": "Fotos oder Ortstermin, damit der Aufwand realistisch eingeschätzt wird."
        },
        {
          "title": "Umfang festlegen",
          "text": "Einmalig oder Vertrag, mit klarer Liste, was enthalten ist."
        },
        {
          "title": "Termine",
          "text": "Feste Turnusse statt Zufall, Sie wissen wann wir kommen."
        },
        {
          "title": "Pflege",
          "text": "Ausführung inklusive Abtransport des Schnittguts."
        }
      ],
      "faq": [
        {
          "q": "Was kostet ein Pflegevertrag?",
          "a": "Das richtet sich nach Fläche, Heckenlänge und Turnus. Nach einem kurzen Blick auf die Fläche nennen wir einen festen Jahresbetrag."
        },
        {
          "q": "Wann wird die Hecke geschnitten?",
          "a": "Der Formschnitt erfolgt außerhalb der gesetzlichen Schonzeit. Radikale Rückschnitte sind vom 1. März bis 30. September nicht zulässig."
        }
      ],
      "image": "/assets/acquisition/projekte/gartenanlage-mit-rasen-und-hecke-01.jpg",
      "estimate": {
        "minPerUnit": 3,
        "maxPerUnit": 12,
        "baseMin": 350
      },
      "seo": {
        "title": "Gartenpflege in Sinsheim | Zogaj Garten & Landschaftsbau",
        "description": "Gartenpflege in Sinsheim als Einmalpflege oder Pflegevertrag: Rasen, Rollrasen, Heckenschnitt und Entsorgung mit festen Terminen."
      }
    },
    {
      "key": "zaun-sichtschutz",
      "slug": "zaun-sichtschutz",
      "label": "Zaun & Sichtschutz",
      "navLabel": "Zaun",
      "cta": "Sichtschutz anfragen",
      "unit": "lfm",
      "teaser": "Doppelstabmatten, Sichtschutzstreifen, Gabionen und Mauern, kalkuliert nach laufenden Metern.",
      "intro": "Zaun und Sichtschutz rechnen sich nach laufenden Metern. Entscheidend sind Höhe, Fundament und Grenzverlauf. Wir sagen vorab, wo eine Genehmigung oder eine Abstimmung mit dem Nachbarn nötig ist, und setzen die Pfosten so, dass die Linie über die ganze Länge steht.",
      "bullets": [
        "Doppelstabmatten mit Sichtschutzstreifen, Holz und Aluminium",
        "Gabionen, Pflanzringe und Stützmauern als feste Abgrenzung",
        "Kalkulation nach laufenden Metern inklusive Pfosten und Fundament",
        "Hinweise zu Grenzbebauung, Höhe und örtlichen Satzungen",
        "Anschluss an Pflaster, Weg und Rasen im selben Zug"
      ],
      "ablauf": [
        {
          "title": "Meter schätzen",
          "text": "Grobe Länge und gewünschte Höhe genügen für die erste Einordnung."
        },
        {
          "title": "Grenze klären",
          "text": "Wir prüfen Verlauf, Untergrund und ob eine Genehmigung nötig ist."
        },
        {
          "title": "Angebot",
          "text": "Material, Pfosten, Fundamente und Tore als getrennte Positionen."
        },
        {
          "title": "Montage",
          "text": "Fundamente setzen, ausrichten, montieren, Baustelle räumen."
        }
      ],
      "faq": [
        {
          "q": "Wie hoch darf der Sichtschutz sein?",
          "a": "Das regeln Landesrecht und örtliche Satzung, häufig sind an der Grenze rund 1,80 m ohne Genehmigung möglich. Wir prüfen den konkreten Fall vor der Montage."
        },
        {
          "q": "Brauche ich Fundamente?",
          "a": "Bei Sichtschutzwänden und Toren ja. Bei leichten Zäunen genügen oft Einschlaghülsen, das entscheidet der Untergrund."
        }
      ],
      "image": "/assets/acquisition/projekte/garten-mit-gerateschuppen-und-rasen-01.jpg",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 320,
        "baseMin": 1200
      },
      "seo": {
        "title": "Zaun & Sichtschutz in Sinsheim | Zogaj Garten & Landschaftsbau",
        "description": "Zaun und Sichtschutz nach laufenden Metern: Doppelstabmatten, Holz, Gabionen, mit Fundament und Hinweisen zur Genehmigung."
      }
    },
    {
      "key": "baumpflege",
      "slug": "baumpflege",
      "label": "Baumpflege & Fällung",
      "navLabel": "Baumpflege",
      "cta": "Baum ansehen lassen",
      "unit": "stk",
      "teaser": "Rückschnitt, Kronenpflege und Fällung, mit Abtransport und Entsorgung des Holzes.",
      "intro": "Bei Bäumen entscheidet der Standort über den Aufwand: Was frei steht, ist schnell erledigt, was über Dach, Zaun oder Leitung hängt, wird Stück für Stück abgetragen. Wir sehen uns den Baum vorher an und sagen offen, ob Pflege reicht oder eine Fällung sinnvoll ist. Holz und Schnittgut nehmen wir mit.",
      "bullets": [
        "Kronenpflege, Auslichten und Einkürzen von Bäumen",
        "Fällung, auch stückweise, wenn kein Fallraum vorhanden ist",
        "Abtransport von Stammholz, Ästen und Wurzelstock",
        "Baum-, Strauch- und Heckenpflanzung als Ersatz",
        "Hinweis auf Schonzeit und örtliche Baumschutzsatzung vorab"
      ],
      "ablauf": [
        {
          "title": "Foto schicken",
          "text": "Ein Bild vom ganzen Baum und vom Umfeld sagt mehr als jede Beschreibung."
        },
        {
          "title": "Vor Ort ansehen",
          "text": "Wir prüfen Zustand, Fallraum, Zufahrt und ob eine Genehmigung nötig ist."
        },
        {
          "title": "Angebot",
          "text": "Arbeit, Absicherung, Abtransport und Entsorgung getrennt ausgewiesen."
        },
        {
          "title": "Ausführung",
          "text": "Absichern, schneiden oder fällen, aufräumen, Fläche besenrein übergeben."
        }
      ],
      "faq": [
        {
          "q": "Darf ich meinen Baum einfach fällen lassen?",
          "a": "Nicht immer. Viele Kommunen haben eine Baumschutzsatzung, die ab einem bestimmten Stammumfang eine Genehmigung verlangt. Wir sagen Ihnen beim Ortstermin, ob das in Ihrem Fall zutrifft, die Genehmigung selbst holt der Eigentümer ein."
        },
        {
          "q": "Wann darf geschnitten werden?",
          "a": "Starke Rückschnitte und Fällungen sind nach dem Bundesnaturschutzgesetz vom 1. März bis 30. September nicht zulässig. Schonender Form- und Pflegeschnitt ist auch in dieser Zeit möglich, solange kein Vogel brütet."
        }
      ],
      "image": "/assets/leistungen/baumpflege-klettertechnik.webp",
      "estimate": {
        "minPerUnit": 150,
        "maxPerUnit": 900,
        "baseMin": 350
      },
      "seo": {
        "title": "Baumpflege & Baumfällung in Sinsheim | Zogaj Garten & Landschaftsbau",
        "description": "Baumpflege und Baumfällung rund um Sinsheim: Kronenpflege, Rückschnitt, stückweise Fällung, Abtransport und Entsorgung."
      }
    }
  ],
  "serviceArea": {
    "centerCity": "Sinsheim",
    "radiusKm": 40,
    "note": "Wir arbeiten im Umkreis von rund 40 km um Sinsheim, zwischen Kraichgau, Heilbronn und Heidelberg. Liegt Ihr Projekt weiter weg, sagen wir Ihnen ehrlich, ob sich die Anfahrt rechnet, statt Sie hinzuhalten.",
    "plzPrefixes": [
      "74",
      "69",
      "75"
    ],
    "borderPlzPrefixes": [
      "76",
      "68",
      "71"
    ],
    "places": [
      "Sinsheim",
      "Bad Rappenau",
      "Waibstadt",
      "Neckarbischofsheim",
      "Angelbachtal",
      "Eppingen",
      "Wiesloch",
      "Walldorf",
      "Bad Schönborn",
      "Östringen",
      "Bruchsal",
      "Heidelberg"
    ],
    "center": {
      "lat": 49.248086,
      "lng": 8.8650877
    }
  },
  "contact": {
    "phone": "0176 32569921",
    "phoneLink": "tel:+4917632569921",
    "whatsapp": "0176 32569921",
    "whatsappLink": "https://wa.me/4917632569921",
    "whatsappPrefill": "Hallo Zogaj Garten & Landschaftsbau, ich habe eine Frage zu einem Gartenprojekt in ",
    "email": "",
    "leadEmail": ""
  },
  "estimator": {
    "enabled": true,
    "minProjectEur": 2500,
    "currency": "EUR",
    "roundingStep": 500,
    "disclaimer": "Alle Angaben sind eine unverbindliche Orientierung, kein Angebot. Der tatsächliche Preis hängt von Boden, Unterbau, Zugang, Entwässerung, Material und Ausführung ab und steht erst nach dem Aufmaß vor Ort fest.",
    "sizeThresholds": {
      "klein": 5000,
      "mittel": 20000
    },
    "surcharges": {
      "hanglage": 0.15,
      "schwererZugang": 0.12,
      "rueckbauBestand": 0.1
    },
    "budgetBands": [
      {
        "id": "bis-5k",
        "label": "bis 5.000 €",
        "min": 0,
        "max": 5000
      },
      {
        "id": "5-15k",
        "label": "5.000 – 15.000 €",
        "min": 5000,
        "max": 15000
      },
      {
        "id": "15-30k",
        "label": "15.000 – 30.000 €",
        "min": 15000,
        "max": 30000
      },
      {
        "id": "30-60k",
        "label": "30.000 – 60.000 €",
        "min": 30000,
        "max": 60000
      },
      {
        "id": "ab-60k",
        "label": "mehr als 60.000 €",
        "min": 60000,
        "max": null
      },
      {
        "id": "unklar",
        "label": "Noch unklar",
        "min": 0,
        "max": null
      }
    ],
    "realismQuestion": "Wäre dieser grobe Rahmen für Sie grundsätzlich realistisch?",
    "realismOptions": [
      {
        "id": "passt",
        "label": "Ja, das passt so"
      },
      {
        "id": "guenstiger",
        "label": "Überraschend günstig"
      },
      {
        "id": "zu-hoch",
        "label": "Zu hoch"
      },
      {
        "id": "unklar",
        "label": "Noch unklar"
      }
    ]
  },
  "recruiting": {
    "enabled": true,
    "headline": "Pflasterer, Landschaftsgärtner oder Quereinsteiger?",
    "teaser": "In 60 Sekunden bewerben. Ohne Lebenslauf, ohne Anschreiben.",
    "intro": "Wir suchen Verstärkung für unsere Baustellen rund um Sinsheim, vor allem für Pflaster- und Erdarbeiten. Sagen Sie uns kurz, was Sie können und wo Sie wohnen, den Rest klären wir am Telefon.",
    "roles": [
      "Landschaftsgärtner/in",
      "Pflasterer/in",
      "Helfer/in Garten- und Landschaftsbau",
      "Quereinsteiger/in"
    ],
    "benefits": [
      "Baustellen im Umkreis von rund 40 km, abends sind Sie zu Hause",
      "Feste Teams, die eine Baustelle bis zur Übergabe begleiten",
      "Werkzeug, Maschinen und Arbeitskleidung werden gestellt",
      "Maschinenscheine und Weiterbildung sind möglich"
    ]
  },
  "trust": {
    "seals": [],
    "usps": [
      {
        "label": "Erst ansehen, dann rechnen",
        "text": "Nach der Anfrage kommt zuerst die Besichtigung vor Ort. Preise nennen wir, wenn wir Fläche, Untergrund und Zufahrt gesehen haben."
      },
      {
        "label": "Im vereinbarten Zeitraum",
        "text": "Der Zeitrahmen steht vor Baubeginn fest. Eine Hofeinfahrt mit rund 160 qm war so in zwei Wochen abgetragen und neu gepflastert."
      },
      {
        "label": "Änderungen sind möglich",
        "text": "Wenn Ihnen während der Bauzeit etwas anderes vorschwebt, gehen wir darauf ein, halten es schriftlich fest und rechnen es offen ab."
      }
    ]
  },
  "assistant": {
    "enabled": true,
    "photoUploadMaxFiles": 6,
    "photoUploadMaxMb": 8,
    "consentText": "Ich bin damit einverstanden, dass meine Angaben zur Bearbeitung meiner Anfrage gespeichert und verarbeitet werden. Die Daten werden nicht an Dritte weitergegeben.",
    "responsePromise": "Wir melden uns in der Regel innerhalb von 24 Stunden an Werktagen."
  }
};

export function findService(slug: string): GalabauService | undefined {
  return galabau.services.find((service) => service.slug === slug);
}

export default galabau;
