// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 5,
  "totalRatings": 23,
  "reviews": [
    {
      "author": "Matthias Mengesdorf",
      "rating": 5,
      "text": "Nur zu Empfehlen! Innerhalb 2 Wochen wurden bei uns über 160qm Hofeinfahrt abgetragen und neu gepflastert. Es wurde alles wie besprochen umgesetzt. Das gesamte Team war immer sehr bemüht und freundlich.",
      "time": "vor 3 Monaten"
    },
    {
      "author": "E P",
      "rating": 5,
      "text": "Das Team hat sehr gute Arbeit geleistet. Auf unsere Wünsche, auch während der Gartengestaltung, wurde voll eingegangen. Sehr gutes Preis-Leistungsverhältnis. In Summe sind wir sehr zufrieden mit unserem neuen Garten.",
      "time": "vor 4 Monaten"
    },
    {
      "author": "Tim S.",
      "rating": 5,
      "text": "Wir sind sehr zufrieden mit den geleisteten Pflasterarbeiten rund um unser Haus. Schnelle Kontaktaufnahme mit Vor-Ort-Besichtigung, gutes Preis-Leistungs-Verhältnis und ein sehr guter Job im vereinbarten Zeitraum. Können wir nur weiterempfehlen.",
      "time": "vor 6 Monaten"
    },
    {
      "author": "Michael Häusler",
      "rating": 5,
      "text": "Super Firma die einen Super Job Macht. Auch bei extra wünsche wurde alles perfekt umgesetzt. Schnelle und professionelle Arbeit. 👍",
      "time": "vor 3 Monaten"
    },
    {
      "author": "Michael Hedrich",
      "rating": 5,
      "text": "Wir können die Firma Zogaj in vollem Umfang empfehlen. Die Kommunikation war einwandfrei. Auf Wünsche wurde eingegangen und Fragen sofort beantwortet.\nDie Umsetzung der Arbeiten war tadellos und das zu fairen Preisen.",
      "time": "vor 7 Monaten"
    }
  ]
};
